#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_webpath_available $domain $path_url \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d $final_path \
	|| ynh_die "There is already a directory: $final_path "

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_restore_file "$final_path"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================

# Create the dedicated user (if not existing)
ynh_system_user_create $app "$final_path"

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chown -R $app: $final_path

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================

# Define and install dependencies
ynh_install_app_dependencies ruby-zip libssl-dev libyaml-dev libcurl4-openssl-dev ruby gem libapr1-dev libxslt1-dev checkinstall libxml2-dev ruby-dev vim libmagickwand-dev imagemagick postgresql postgresql-server-dev-all

#=================================================
# RESTORE THE POSTGRES DATABASE
#=================================================

db_pwd=$(ynh_app_setting_get $app psqlpwd)
# Restore database
ynh_psql_test_if_first_run
ynh_psql_create_db $db_name $db_name $db_pwd

su -c "psql $db_name" postgres < db.sql

#=================================================
# SETUP PUMA, A RUBY SERVER
#=================================================

# Install puma with gem
(cd "$final_path"
# Install bundler, a gems installer
gem install bundler)
# Add puma to the dependencies
# exec_as $app echo "gem 'puma'" >> Gemfile.local
# # Install without documentation. Why ...?
# exec_as $app echo "gem: --no-ri --no-rdoc" >> "$final_path/.gemrc"
# # Install dependencies
# exec_as $app bundle install --path vendor/bundle --without development test postgresql)

# Set permissions to app files
# chown -R $app: $final_path

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add $app --log "/var/log/$app/puma.stderr.log"

#=================================================
# RESTORE SYSVINIT
#=================================================

ynh_restore_file "/etc/init.d/redmine"
update-rc.d $app defaults

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================

ynh_restore_file "/etc/logrotate.d/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# START PUMA AND REDMINE
#=================================================

systemctl start $app
